[package]
name = "websocket"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
futures-util = "0.3"
tokio = { version = "1.46", features = ["rt-multi-thread", "parking_lot"] }
